<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$dictionary['C_Payment'] = array(
	'table'=>'c_payment',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'payment_date_1' => 
  array (
    'required' => false,
    'name' => 'payment_date_1',
    'vname' => 'LBL_PAYMENT_DATE_1',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'payment_date_2' => 
  array (
    'required' => false,
    'name' => 'payment_date_2',
    'vname' => 'LBL_PAYMENT_DATE_2',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Date 2',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'full_payment_date' => 
  array (
    'required' => false,
    'name' => 'full_payment_date',
    'vname' => 'LBL_FULL_PAYMENT_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Full-payment Date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'payment_amount_1' => 
  array (
    'required' => false,
    'name' => 'payment_amount_1',
    'vname' => 'LBL_PAYMENT_AMOUNT_1',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Amount 1',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'payment_amount_2' => 
  array (
    'required' => false,
    'name' => 'payment_amount_2',
    'vname' => 'LBL_PAYMENT_AMOUNT_2',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Amount 2',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'payment_method_1' => 
  array (
    'required' => false,
    'name' => 'payment_method_1',
    'vname' => 'LBL_PAYMENT_METHOD_1',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Cash',
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Method 1',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'payment_method_options',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'payment_method_2' => 
  array (
    'required' => false,
    'name' => 'payment_method_2',
    'vname' => 'LBL_PAYMENT_METHOD_2',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Cash',
    'no_default' => false,
    'comments' => '',
    'help' => 'Payment Method 2',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'payment_method_options',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'full_payment_method' => 
  array (
    'required' => false,
    'name' => 'full_payment_method',
    'vname' => 'LBL_FULL_PAYMENT_METHOD',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Cash',
    'no_default' => false,
    'comments' => '',
    'help' => 'Full-payment Method',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'payment_method_options',
    'studio' => 'visible',
    'dependency' => false,
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('C_Payment','C_Payment', array('basic','team_security','assignable'));