<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'product_templates_created_by' => 
  array (
    'id' => '1bec7d2f-8550-fb0a-ba2b-5546e8f69ba5',
    'relationship_name' => 'product_templates_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'ProductTemplates',
    'rhs_table' => 'product_templates',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'producttemplates_c_hotel_1' => 
  array (
    'id' => '2771445c-3314-4b53-c977-5546e81a525a',
    'relationship_name' => 'producttemplates_c_hotel_1',
    'lhs_module' => 'ProductTemplates',
    'lhs_table' => 'product_templates',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Hotel',
    'rhs_table' => 'c_hotel',
    'rhs_key' => 'id',
    'join_table' => 'producttemplates_c_hotel_1_c',
    'join_key_lhs' => 'producttemplates_c_hotel_1producttemplates_ida',
    'join_key_rhs' => 'producttemplates_c_hotel_1c_hotel_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'producttemplates_c_tour_1' => 
  array (
    'id' => '2fa2636c-3d8c-1a52-ce51-5546e8ba3206',
    'relationship_name' => 'producttemplates_c_tour_1',
    'lhs_module' => 'ProductTemplates',
    'lhs_table' => 'product_templates',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Tour',
    'rhs_table' => 'c_tour',
    'rhs_key' => 'id',
    'join_table' => 'producttemplates_c_tour_1_c',
    'join_key_lhs' => 'producttemplates_c_tour_1producttemplates_ida',
    'join_key_rhs' => 'producttemplates_c_tour_1c_tour_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'product_templates_modified_user' => 
  array (
    'id' => 'cad40645-407e-442e-6de3-5546e8cca03f',
    'relationship_name' => 'product_templates_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'ProductTemplates',
    'rhs_table' => 'product_templates',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'producttemplates_opportunities_1' => 
  array (
    'rhs_label' => 'Opportunities',
    'lhs_label' => 'Product Catalog',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'ProductTemplates',
    'rhs_module' => 'Opportunities',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'producttemplates_opportunities_1',
  ),
);