<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_BookingTour'] = array(
        'table'=>'c_bookingtour',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'status' => 
            array (
                'required' => true,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => 'Comfirmation',
                'no_default' => false,
                'comments' => '',
                'help' => 'Status',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_booking_tour_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'deadline' => 
            array (
                'required' => false,
                'name' => 'deadline',
                'vname' => 'LBL_DEADLINE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Deadline',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'booking_date' => 
            array (
                'required' => false,
                'name' => 'booking_date',
                'vname' => 'LBL_BOOKING_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Booking Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'booking_name' => 
            array (
                'required' => false,
                'name' => 'booking_name',
                'vname' => 'LBL_BOOKING_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Booking Name',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'start_date' => 
            array (
                'required' => false,
                'name' => 'start_date',
                'vname' => 'LBL_START_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Start Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'end_date' => 
            array (
                'required' => false,
                'name' => 'end_date',
                'vname' => 'LBL_END_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'End Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'price_adult' => 
            array (
                'required' => false,
                'name' => 'price_adult',
                'vname' => 'LBL_PRICE_ADULT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price Adult',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'price_chd' => 
            array (
                'required' => false,
                'name' => 'price_chd',
                'vname' => 'LBL_PRICE_CHD',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price CHD',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'price_infant' => 
            array (
                'required' => false,
                'name' => 'price_infant',
                'vname' => 'LBL_PRICE_INFANT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price Infant',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'adult' => 
            array (
                'required' => false,
                'name' => 'adult',
                'vname' => 'LBL_ADULT',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Adult',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'children' => 
            array (
                'required' => false,
                'name' => 'children',
                'vname' => 'LBL_CHILDREN',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Children',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'infant' => 
            array (
                'required' => false,
                'name' => 'infant',
                'vname' => 'LBL_INFANT',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Infant',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'penalty_percent' => 
            array (
                'required' => false,
                'name' => 'penalty_percent',
                'vname' => 'LBL_PENALTY_PERCENT',
                'type' => 'decimal',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Penalty %',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'discount_percent' => 
            array (
                'required' => false,
                'name' => 'discount_percent',
                'vname' => 'LBL_DISCOUNT_PERCENT',
                'type' => 'decimal',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Discount %',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'invoice_no' => 
            array (
                'required' => false,
                'name' => 'invoice_no',
                'vname' => 'LBL_INVOICE_NO',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice No',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'prepay_amount' => 
            array (
                'required' => false,
                'name' => 'prepay_amount',
                'vname' => 'LBL_PREPAY_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Prepay Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'total_amount' => 
            array (
                'required' => false,
                'name' => 'total_amount',
                'vname' => 'LBL_TOTAL_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Total Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'sub_total' => 
            array (
                'required' => false,
                'name' => 'sub_total',
                'vname' => 'LBL_SUB_TOTAL',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Sub Total',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'discount_amount' => 
            array (
                'required' => false,
                'name' => 'discount_amount',
                'vname' => 'LBL_DISCOUNT_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Discount Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'penalty_amount' => 
            array (
                'required' => false,
                'name' => 'penalty_amount',
                'vname' => 'LBL_PENALTY_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Penalty Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            
            'invoice_serial_no' => 
            array (
                'required' => false,
                'name' => 'invoice_serial_no',
                'vname' => 'LBL_INVOICE_SERIAL_NO',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice Serial No',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'invoice_date' => 
            array (
                'required' => false,
                'name' => 'invoice_date',
                'vname' => 'LBL_INVOICE_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'tour_details' => 
            array (
                'required' => false,
                'name' => 'tour_details',
                'vname' => 'LBL_TOUR_DETAILS',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'tour_details',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),
            'tour_policy' => 
            array (
                'required' => false,
                'name' => 'tour_policy',
                'vname' => 'LBL_TOUR_POLICY',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'tour_policy',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),

            'parent_name' => array(
                'name' => 'parent_name',
                'vname' => 'LBL_PARENT_NAME',
                'type' => 'parent',
                'massupdate' => 0,
                'dbtype' => 'varchar',
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'len' => 100,
                'size' => '20',
                'options' => 'flexparent_booking_hotel_list',
                'studio' => 'visible',
                'type_name' => 'parent_type',
                'id_name' => 'parent_id',
                'parent_type' => 'flexparent_booking_hotel_list',
            ),
            'parent_type' => array(
                'required' => false,
                'name' => 'parent_type',
                'vname' => 'LBL_PARENT_TYPE',
                'type' => 'parent_type',
                'massupdate' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'len' => 255,
                'size' => '20',
                'default' => 'Accounts',
                'dbType' => 'varchar',
                'studio' => 'hidden',
            ),
            'parent_id' => array(
                'required' => false,
                'name' => 'parent_id',
                'vname' => 'LBL_PARENT_ID',
                'type' => 'id',
                'massupdate' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'len' => 36,
                'size' => '20',
            ),
            'user_manager' =>  array (
                'name' => 'user_manager',
                'rname' => 'name',
                'id_name' => 'user_manager_id',
                'vname' => 'LBL_USER_MANAGER',
                'type' => 'relate',
                'link'=>'users',
                'table' => 'users',
                'join_name'=>'users',
                'module' => 'Users',
                'dbType' => 'varchar',
                'len' => 100,
                'source'=>'non-db',
                'massupdate' => 0,
            ),
            'user_manager_id' =>  array (
                'name'=>'user_manager_id',
                'type' => 'relate',
                'dbType' => 'id',
                'rname' => 'id',
                'module' => 'Users',
                'massupdate' => 0,
            ),
            'users' =>  array (
                'name' => 'users',
                'type' => 'link',
                'source'=>'non-db',
                'massupdate' => 0,  
            ),
            'address' => 
            array (
                'name' => 'address',
                'vname' => 'LBL_ADDRESS',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Address',
                'importable' => 'true',
                'len' => 100,
                'size' => '20',
                'rows' => '3',
                'cols' => '60',
            ),
            'email' =>
            array(
                'required' => false,
                'name' => 'email',
                'vname' => 'LBL_EMAIL',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Email',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),                     
            'tax_code' => 
            array (
                'required' => false,
                'name' => 'tax_code',
                'vname' => 'LBL_TAX_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Tax Code',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'phone' =>
            array (
                'name' => 'phone',
                'vname' => 'LBL_PHONE',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => 100,
                'unified_search' => true, 
                'full_text_search' => array('boost' => 1),
                'merge_filter' => 'enabled',
            ),
            'filename' =>
            array (
                'name' => 'filename',
                'vname' => 'LBL_FILENAME',
                'type' => 'varchar',
                'required'=>true,
                'importable' => 'required',
                'len' => '255',
                'studio' => 'false',
            ),
            'file_ext' =>
            array (
                'name' => 'file_ext',
                'vname' => 'LBL_FILE_EXTENSION',
                'type' => 'varchar',
                'len' => 100,
            ),
            'file_mime_type' =>
            array (
                'name' => 'file_mime_type',
                'vname' => 'LBL_MIME',
                'type' => 'varchar',
                'len' => '100',
            ),
            'uploadfile' =>
            array (
                'name'=>'uploadfile',
                'vname' => 'LBL_FILE_UPLOAD',
                'type' => 'file',
                'source' => 'non-db',
            ),
            //payment info
            'payment_date_1' => 
            array (
                'required' => false,
                'name' => 'payment_date_1',
                'vname' => 'LBL_PAYMENT_DATE_1',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Date 1',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'payment_amount_1' => 
            array (
                'required' => false,
                'name' => 'payment_amount_1',
                'vname' => 'LBL_PAYMENT_AMOUNT_1',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount 1',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payment_date_2' => 
            array (
                'required' => false,
                'name' => 'payment_date_2',
                'vname' => 'LBL_PAYMENT_DATE_2',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Date 2',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'payment_amount_2' => 
            array (
                'required' => false,
                'name' => 'payment_amount_2',
                'vname' => 'LBL_PAYMENT_AMOUNT_2',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount 2',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'full_payment_date' => 
            array (
                'required' => false,
                'name' => 'full_payment_date',
                'vname' => 'LBL_FULL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Full-payment Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'payment_method_1' => array(
                'name' => 'payment_method_1',
                'vname' => 'LBL_PAYMENT_METHOD_1',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'payment_method_2' => array(
                'name' => 'payment_method_2',
                'vname' => 'LBL_PAYMENT_METHOD_2',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'full_payment_method' => array(
                'name' => 'full_payment_method',
                'vname' => 'LBL_FULL_PAYMENT_METHOD',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'tour_code' => array(
                'name' => 'tour_code',
                'vname' => 'LBL_TOUR_CODE',
                'type' => 'varchar',
                'unified_search' => true,
                'importable' => 'required',
                'help' => 'Tour Code',
                'len' => '50',
                'size' => '20',
            ),
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_BookingTour','C_BookingTour', array('basic','team_security','assignable'));