<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_Tour'] = array(
        'table'=>'c_tour',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            
            'option_tour' => 
            array (
                'required' => false,
                'name' => 'option_tour',
                'vname' => 'LBL_OPTION_TOUR',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => 'Domestic',
                'no_default' => false,
                'comments' => '',
                'help' => 'Option',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'option_tour_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'days' => 
            array (
                'required' => false,
                'name' => 'days',
                'vname' => 'LBL_DAYS',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Days',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'night' => 
            array (
                'required' => false,
                'name' => 'night',
                'vname' => 'LBL_NIGHT',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Night',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'price_adult' => 
            array (
                'required' => false,
                'name' => 'price_adult',
                'vname' => 'LBL_PRICE_ADULT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price Adult',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'price_chd' => 
            array (
                'required' => false,
                'name' => 'price_chd',
                'vname' => 'LBL_PRICE_CHD',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price CHD',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'price_infant' => 
            array (
                'required' => false,
                'name' => 'price_infant',
                'vname' => 'LBL_PRICE_INFANT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Price Infant',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'start_date' => 
            array (
                'required' => false,
                'name' => 'start_date',
                'vname' => 'LBL_START_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Start Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'end_date' => 
            array (
                'required' => false,
                'name' => 'end_date',
                'vname' => 'LBL_END_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'End Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'contact_phone' => 
            array (
                'name' => 'contact_phone',
                'vname' => 'LBL_CONTACT_PHONE',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => 100,
                'unified_search' => true, 
                'full_text_search' => array('boost' => 1),
                'comment' => 'Home phone number of the contact',
                'merge_filter' => 'enabled',
            ),
            'tour_details' => 
            array (
                'required' => false,
                'name' => 'tour_details',
                'vname' => 'LBL_TOUR_DETAILS',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'tour_details',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),
            'tour_policy' => 
            array (
                'required' => false,
                'name' => 'tour_policy',
                'vname' => 'LBL_TOUR_POLICY',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'tour_policy',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),
            'salutation' => 
            array (
                'required' => false,
                'name' => 'salutation',
                'vname' => 'LBL_SALUTATION',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'salutation',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'salutation_dom',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'contact_name' => 
            array (
                'required' => false,
                'name' => 'contact_name',
                'vname' => 'LBL_CONTACT_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Contact Name',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'filename' =>
            array (
                'name' => 'filename',
                'vname' => 'LBL_FILENAME',
                'type' => 'varchar',
                'required'=>true,
                'importable' => 'true',
                'len' => '255',
                'studio' => 'false',
            ),
            'file_ext' =>
            array (
                'name' => 'file_ext',
                'vname' => 'LBL_FILE_EXTENSION',
                'type' => 'varchar',
                'len' => 100,
            ),
            'file_mime_type' =>
            array (
                'name' => 'file_mime_type',
                'vname' => 'LBL_MIME',
                'type' => 'varchar',
                'len' => '100',
            ),
            'uploadfile' =>
            array (
                'name'=>'uploadfile',
                'vname' => 'LBL_FILE_UPLOAD',
                'type' => 'file',
                'source' => 'non-db',
            ),
            'code' => array(
                'name' => 'code',
                'vname' => 'LBL_CODE',
                'type' => 'varchar',
                'unified_search' => true,
                'importable' => 'true',
                'help' => 'Code',
                'len' => '50',
                'size' => '20',
            ),
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Tour','C_Tour', array('basic','team_security','assignable'));