<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_bookinghotel_c_payment_1' => 
  array (
    'id' => '3c2311b2-21e8-6d7e-2c27-5559aecd9a2b',
    'relationship_name' => 'c_bookinghotel_c_payment_1',
    'lhs_module' => 'C_BookingHotel',
    'lhs_table' => 'c_bookinghotel',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'id',
    'join_table' => 'c_bookinghotel_c_payment_1_c',
    'join_key_lhs' => 'c_bookinghotel_c_payment_1c_bookinghotel_ida',
    'join_key_rhs' => 'c_bookinghotel_c_payment_1c_payment_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_bookingticket_c_payment_1' => 
  array (
    'id' => '5a4f020e-44af-b62d-e91d-5559aeb324cd',
    'relationship_name' => 'c_bookingticket_c_payment_1',
    'lhs_module' => 'C_BookingTicket',
    'lhs_table' => 'c_bookingticket',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'id',
    'join_table' => 'c_bookingticket_c_payment_1_c',
    'join_key_lhs' => 'c_bookingticket_c_payment_1c_bookingticket_ida',
    'join_key_rhs' => 'c_bookingticket_c_payment_1c_payment_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_payment_modified_user' => 
  array (
    'id' => '6c1cdfcf-ffbb-8ca4-0082-5559ae6e3d53',
    'relationship_name' => 'c_payment_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'c_bookingtour_c_payment_1' => 
  array (
    'id' => '73c560a7-81bf-f8d3-8cfb-5559ae1be022',
    'relationship_name' => 'c_bookingtour_c_payment_1',
    'lhs_module' => 'C_BookingTour',
    'lhs_table' => 'c_bookingtour',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'id',
    'join_table' => 'c_bookingtour_c_payment_1_c',
    'join_key_lhs' => 'c_bookingtour_c_payment_1c_bookingtour_ida',
    'join_key_rhs' => 'c_bookingtour_c_payment_1c_payment_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_payment_created_by' => 
  array (
    'id' => '8645f50d-c3be-0b06-a7a4-5559ae47ae57',
    'relationship_name' => 'c_payment_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'c_payment_assigned_user' => 
  array (
    'id' => 'a1669705-82f0-d0fe-9c77-5559ae3f1a49',
    'relationship_name' => 'c_payment_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payment',
    'rhs_table' => 'c_payment',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
);