<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_Ticket'] = array(
        'table'=>'c_ticket',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'category' => 
            array (
                'required' => false,
                'name' => 'category',
                'vname' => 'LBL_CATEGORY',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Category',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'category_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'sub_category' => 
            array (
                'required' => false,
                'name' => 'sub_category',
                'vname' => 'LBL_SUB_CATEGORY',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Sub Category',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'sub_category_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),

            'supplier' => 
            array (
                'required' => false,
                'name' => 'supplier',
                'vname' => 'LBL_SUPPLIER',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Supplier',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'supplier_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),


            'airline' => 
            array (
                'required' => false,
                'name' => 'airline',
                'vname' => 'LBL_ASSET',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'help' => 'Airline',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'options' => 'asset_ticket_list',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'tour' => 
            array (
                'required' => false,
                'name' => 'tour',
                'vname' => 'LBL_TOUR',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Tour',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => true,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'refund_code' => 
            array (
                //'required' => true,
                'name' => 'refund_code',
                'vname' => 'LBL_REFUND_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Refund Code',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'routing' => 
            array (
                'required' => false,
                'name' => 'routing',
                'vname' => 'LBL_ROUTING',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Routing',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'pax_name' => 
            array (
                'required' => true,
                'name' => 'pax_name',
                'vname' => 'LBL_PAX_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Pax name',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => true,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'membership_number' => 
            array (
                'required' => false,
                'name' => 'membership_number',
                'vname' => 'LBL_MEMBERSHIP_NUMBER',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Membership Number',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'card_type' => 
            array (
                'required' => false,
                'name' => 'card_type',
                'vname' => 'LBL_CARD_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Card Type',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'card_type_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'booking_code' => 
            array (
                'required' => false,
                'name' => 'booking_code',
                'vname' => 'LBL_BOOKING_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Booking Code (PNR)',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'dateline' => 
            array (
                'required' => false,
                'name' => 'dateline',
                'vname' => 'LBL_DATELINE',
                'type' => 'datetimecombo',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Dateline',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'dbType' => 'datetime',
                'display_default' => '+1 week&03:15pm',
            ),
            'gateway' => 
            array (
                'required' => false,
                'name' => 'gateway',
                'vname' => 'LBL_GATEWAY',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Gateway',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'class' => 
            array (
                'required' => false,
                'name' => 'class',
                'vname' => 'LBL_CLASS',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Class',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'class_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'fare_basic' => 
            array (
                'required' => false,
                'name' => 'fare_basic',
                'vname' => 'LBL_FARE_BASIC',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Fare Basic',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'public_fare' => 
            array (
                'required' => false,
                'name' => 'public_fare',
                'vname' => 'LBL_PUBLIC_FARE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Public Fare',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY_UNIT',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'market_fare' => 
            array (
                'required' => false,
                'name' => 'market_fare',
                'vname' => 'LBL_MARKET_FARE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Market Fare',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'commission_percent' => 
            array (
                'required' => false,
                'name' => 'commission_percent',
                'vname' => 'LBL_COMMISSION_PERCENT',
                'type' => 'decimal',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Commission percent',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => '2',
            ),
            'commission' => 
            array (
                'required' => false,
                'name' => 'commission',
                'vname' => 'LBL_COMMISSION',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Commission',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'net_fare' => 
            array (
                'required' => false,
                'name' => 'net_fare',
                'vname' => 'LBL_NET_FARE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Net Fare',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'discount_percent' => 
            array (
                'required' => false,
                'name' => 'discount_percent',
                'vname' => 'LBL_DISCOUNT_PERCENT',
                'type' => 'decimal',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Discount percent',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => '2',
            ),
            'discount' => 
            array (
                'required' => false,
                'name' => 'discount',
                'vname' => 'LBL_DISCOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Discount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'airport_tax' => 
            array (
                'required' => false,
                'name' => 'airport_tax',
                'vname' => 'LBL_AIRPORT_TAX',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Airport Tax',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'vat_percent' => 
            array (
                'required' => false,
                'name' => 'vat_percent',
                'vname' => 'LBL_VAT_PERCENT',
                'type' => 'decimal',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'VAT percent',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => '2',
            ),
            'vat_amount' => 
            array (
                'required' => false,
                'name' => 'vat_amount',
                'vname' => 'LBL_VAT_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'VAT Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'service_charge' => 
            array (
                'required' => false,
                'name' => 'service_charge',
                'vname' => 'LBL_SERVICE_CHARGE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Service Charge',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'service_charge_vnd' => 
            array (
                'required' => false,
                'name' => 'service_charge_vnd',
                'vname' => 'LBL_SERVICE_CHARG_VND',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Service Charge VND',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'receivable' => 
            array (
                'required' => false,
                'name' => 'receivable',
                'vname' => 'LBL_RECEIVABLE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Receivable',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payable' => 
            array (
                'required' => false,
                'name' => 'payable',
                'vname' => 'LBL_PAYABLE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payalbe',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'earn' => 
            array (
                'required' => false,
                'name' => 'earn',
                'vname' => 'LBL_EARN',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'EARN',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'refund_fee' => 
            array (
                'required' => false,
                'name' => 'refund_fee',
                'vname' => 'LBL_REFUND_FEE',
                'type' => 'currency',
                'no_default' => false,
                'help' => 'Refund Fee',
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'refund_fee_airline' => 
            array (
                'required' => false,
                'name' => 'refund_fee_airline',
                'vname' => 'LBL_REFUND_FEE_AIRLINE',
                'type' => 'currency',
                'no_default' => false,
                'help' => 'Refund Fee for Airline',
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'repay_client' => 
            array (
                'required' => false,
                'name' => 'repay_client',
                'vname' => 'LBL_REPAY_CLIENT',
                'type' => 'currency',
                'no_default' => false,
                'help' => 'Repay Client',
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'airline_repay' => 
            array (
                'required' => false,
                'name' => 'airline_repay',
                'vname' => 'LBL_AIRLINE_REPAY',
                'type' => 'currency',
                'no_default' => false,
                'help' => 'Airline Repay',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'refunded' =>
            array (
                'name' => 'refunded',
                'vname' => 'LBL_REFUNDED',
                'type' => 'bool',
                'help' => 'Refunded',
                'audited' => true,
                'default' => '0',
            ),
            'refund_date' => 
            array (
                'required' => false,
                'name' => 'refund_date',
                'vname' => 'LBL_REFUND_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Refund Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'currency' => 
            array (
                'required' => true,
                'name' => 'currency',
                'vname' => 'LBL_CURRENCY',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'VND',
                'comments' => '',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 30,
                'size' => '20',
                'options' => 'currency_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'ex_rate' => 
            array (
                'required' => false,
                'name' => 'ex_rate',
                'vname' => 'LBL_EX_RATE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Ex rate',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '13',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            'booking_date' => 
            array (
                'required' => false,
                'name' => 'booking_date',
                'vname' => 'LBL_BOOKING_DATE',
                'type' => 'date',
                'massupdate' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => 'Booking Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
            ),
            'temp_field' => 
            array (
                'required' => false,
                'name' => 'temp_field',
                'vname' => 'LBL_TMEP_FIELD',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '1',
                'size' => '20',
            ),
            'unit_code' => 
            array (
                'required' => false,
                'name' => 'unit_code',
                'vname' => 'LBL_UNIT_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '10',
                'size' => '20',
            ),
            'io_code' => 
            array (
                'name' => 'io_code',
                'vname' => 'LBL_IO_CODE',
                'type' => 'enum',
                'comments' => '',
                'help' => 'Mã nhập xuất',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'full_IO_code_list',
                'studio' => 'visible',
                'dependency' => false,
                'massupdate' => 0,
            ),
            'document_id' => 
            array (
                'required' => false,
                'name' => 'document_id',
                'vname' => 'LBL_DOCUMENT_ID',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Internal Document ID',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'invoice_no' => 
            array (
                'required' => false,
                'name' => 'invoice_no',
                'vname' => 'LBL_INVOICE_NO',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice No',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'invoice_date' => 
            array (
                'required' => false,
                'name' => 'invoice_date',
                'vname' => 'LBL_INVOICE_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
            ),
            'supplier' => 
            array (
                'required' => false,
                'name' => 'supplier',
                'vname' => 'LBL_SUPPLIER',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Supplier',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'supplier_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'full_payment_date' => 
            array (
                'required' => false,
                'name' => 'full_payment_date',
                'vname' => 'LBL_FULL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Full-payment Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'full_payment_method' => array(
                'name' => 'full_payment_method',
                'vname' => 'LBL_FULL_PAYMENT_METHOD',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'customer_code' => 
            array (
                'required' => false,
                'name' => 'customer_code',
                'vname' => 'LBL_CUSTOMER_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'sale_code' => 
            array (
                'required' => false,
                'name' => 'sale_code',
                'vname' => 'LBL_SALE_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'ticketing_code' => 
            array (
                'required' => false,
                'name' => 'ticketing_code',
                'vname' => 'LBL_TICKETING_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'ticket_index' => 
            array (
                'required' => false,
                'name' => 'ticket_index',
                'vname' => 'LBL_TICKET_INDEX',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'status' => 
            array (
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'comments' => '',
                'help' => 'Status',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_booking_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
                'default' => 'WaitingList',
                'massupdate' => 0,
            ),
            //Related Field  - Fisrt Aproach
            'user_sale' =>  array (
                'required' => true,
                'name' => 'user_sale',
                'vname' => 'LBL_USER_SALE',
                'type' => 'relate',
                'reportable'=>false,
                'link' => 'users_sale',
                'rname' => 'name',
                'table' => 'users',
                'id_name' => 'user_sale_id',
                'module'=>'Users',
                'duplicate_merge'=>'disabled',
                'importable' => 'false',
                'massupdate' => false,
                'massupdate' => 0,
            ),
            'user_sale_id' =>  array (
                'required' => true,
                'name' => 'user_sale_id',
                'rname' => 'user_sale',
                'id_name' => 'user_sale_id',
                'vname' => 'LBL_USER_SALE_ID',
                'type' => 'assigned_user_name',
                'table' => 'users',
                'isnull' => 'false',
                'dbType' => 'id',
                'group'=>'user_sale',
                'comment' => 'User who sale ticket',
                'massupdate' => false,
                'massupdate' => 0,
            ),
            'users_sale' =>  array (
                'name' => 'users_sale',
                'type' => 'link',
                'relationship' => 'users_sale',
                'vname' => 'LBL_USER_SALE',
                'link_type' => 'one',
                'module'=>'Users',
                'bean_name'=>'User',
                'source'=>'non-db',
                'massupdate' => 0,
            ),
            //End Field User Sale
            'sale_email' => 
            array (
                'required' => false,
                'name' => 'sale_email',
                'vname' => 'LBL_SALE_EMAIL',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Sale Email',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),


        ),
        'relationships'=>array (
            //Relationship User Sale
            'users_sale' => array(
                'lhs_module'=> 'Users', 
                'lhs_table'=> 'users', 
                'lhs_key' => 'id',
                'rhs_module'=> 'C_Ticket', 
                'rhs_table'=> 'c_ticket', 
                'rhs_key' => 'user_sale_id',
                'relationship_type'=>'one-to-many')
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Ticket','C_Ticket', array('basic','team_security','assignable'));