<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_Hotel'] = array(
        'table'=>'c_hotel',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (

            'star' => 
            array (
                'required' => false,
                'name' => 'star',
                'vname' => 'LBL_STAR',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Star',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '5',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'address_street' => 
            array (
                'required' => false,
                'name' => 'address_street',
                'vname' => 'LBL_ADDRESS_STREET',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'group' => 'address',
            ),
            'address_city' => 
            array (
                'required' => false,
                'name' => 'address_city',
                'vname' => 'LBL_ADDRESS_CITY',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'group' => 'address',
            ),
            'address_state' => 
            array (
                'required' => false,
                'name' => 'address_state',
                'vname' => 'LBL_ADDRESS_STATE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'group' => 'address',
            ),
            'address_postalcode' => 
            array (
                'required' => false,
                'name' => 'address_postalcode',
                'vname' => 'LBL_ADDRESS_POSTALCODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 20,
                'size' => '20',
                'group' => 'address',
            ),
            'address_country' => 
            array (
                'required' => false,
                'name' => 'address_country',
                'vname' => 'LBL_ADDRESS_COUNTRY',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'group' => 'address',
            ),
            'contact_phone' => 
            array (
                'name' => 'contact_phone',
                'vname' => 'LBL_CONTACT_PHONE',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => 100,
                'unified_search' => true, 
                'full_text_search' => array('boost' => 1),
                'comment' => '',
                'merge_filter' => 'enabled',
            ),
            'hotel_details' => 
            array (
                'required' => false,
                'name' => 'hotel_details',
                'vname' => 'LBL_HOTEL_DETAILS',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'hotel_details',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),
            'hotel_policy' => 
            array (
                'required' => false,
                'name' => 'hotel_policy',
                'vname' => 'LBL_HOTEL_POLICY',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'hotel_policy',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '80',
            ),
            'salutation' => 
            array (
                'required' => false,
                'name' => 'salutation',
                'vname' => 'LBL_SALUTATION',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'salutation',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'salutation_dom',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'contact_name' => 
            array (
                'required' => false,
                'name' => 'contact_name',
                'vname' => 'LBL_CONTACT_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Contact Name',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'filename' =>
            array (
                'name' => 'filename',
                'vname' => 'LBL_FILENAME',
                'type' => 'varchar',
                'required'=>true,
                'importable' => 'true',
                'len' => '255',
                'studio' => 'false',
            ),
            'file_ext' =>
            array (
                'name' => 'file_ext',
                'vname' => 'LBL_FILE_EXTENSION',
                'type' => 'varchar',
                'len' => 100,
            ),
            'file_mime_type' =>
            array (
                'name' => 'file_mime_type',
                'vname' => 'LBL_MIME',
                'type' => 'varchar',
                'len' => '100',
            ),
            'uploadfile' =>
            array (
                'name'=>'uploadfile',
                'vname' => 'LBL_FILE_UPLOAD',
                'type' => 'file',
                'source' => 'non-db',
            ),
            'code' => array(
                'name' => 'code',
                'vname' => 'LBL_CODE',
                'type' => 'varchar',
                'unified_search' => true,
                'importable' => 'true',
                'help' => 'Code',
                'len' => '50',
                'size' => '20',
            ),

        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Hotel','C_Hotel', array('basic','team_security','assignable'));