<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'accounts_c_bookinghotel_1' => 
  array (
    'id' => '2a781eb1-44d5-4f8f-bdde-5559a8c1570e',
    'relationship_name' => 'accounts_c_bookinghotel_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'id',
    'join_table' => 'accounts_c_bookinghotel_1_c',
    'join_key_lhs' => 'accounts_c_bookinghotel_1accounts_ida',
    'join_key_rhs' => 'accounts_c_bookinghotel_1c_bookinghotel_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_c_bookinghotel_1' => 
  array (
    'id' => '4c82db20-9f7c-3a84-4068-5559a89d37e1',
    'relationship_name' => 'contacts_c_bookinghotel_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'id',
    'join_table' => 'contacts_c_bookinghotel_1_c',
    'join_key_lhs' => 'contacts_c_bookinghotel_1contacts_ida',
    'join_key_rhs' => 'contacts_c_bookinghotel_1c_bookinghotel_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_bookinghotel_c_room_1' => 
  array (
    'id' => '6763cea1-21c2-4f9f-ca7e-5559a8415795',
    'relationship_name' => 'c_bookinghotel_c_room_1',
    'lhs_module' => 'C_BookingHotel',
    'lhs_table' => 'c_bookinghotel',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Room',
    'rhs_table' => 'c_room',
    'rhs_key' => 'id',
    'join_table' => 'c_bookinghotel_c_room_1_c',
    'join_key_lhs' => 'c_bookinghotel_c_room_1c_bookinghotel_ida',
    'join_key_rhs' => 'c_bookinghotel_c_room_1c_room_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_hotel_c_bookinghotel_1' => 
  array (
    'id' => '829ad9cd-5e37-6438-d41d-5559a8c91bad',
    'relationship_name' => 'c_hotel_c_bookinghotel_1',
    'lhs_module' => 'C_Hotel',
    'lhs_table' => 'c_hotel',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'id',
    'join_table' => 'c_hotel_c_bookinghotel_1_c',
    'join_key_lhs' => 'c_hotel_c_bookinghotel_1c_hotel_ida',
    'join_key_rhs' => 'c_hotel_c_bookinghotel_1c_bookinghotel_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_bookinghotel_modified_user' => 
  array (
    'id' => '9f9ba0ed-31c9-7544-47b5-5559a8264528',
    'relationship_name' => 'c_bookinghotel_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'opportunities_c_bookinghotel_1' => 
  array (
    'id' => 'a068d70d-3547-4e54-6976-5559a82687dd',
    'relationship_name' => 'opportunities_c_bookinghotel_1',
    'lhs_module' => 'Opportunities',
    'lhs_table' => 'opportunities',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'id',
    'join_table' => 'opportunities_c_bookinghotel_1_c',
    'join_key_lhs' => 'opportunities_c_bookinghotel_1opportunities_ida',
    'join_key_rhs' => 'opportunities_c_bookinghotel_1c_bookinghotel_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_bookinghotel_created_by' => 
  array (
    'id' => 'a57f2885-199b-7284-fbd0-5559a809547f',
    'relationship_name' => 'c_bookinghotel_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_bookinghotel_assigned_user' => 
  array (
    'id' => 'c0b03d6c-2b7c-3edf-88c7-5559a8218b15',
    'relationship_name' => 'c_bookinghotel_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_BookingHotel',
    'rhs_table' => 'c_bookinghotel',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_bookinghotel_c_payment_1' => 
  array (
    'rhs_label' => 'Payment',
    'lhs_label' => 'Booking Hotel',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'C_BookingHotel',
    'rhs_module' => 'C_Payment',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_bookinghotel_c_payment_1',
  ),
);