<?PHP
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN book_BookingTicket
 */


class book_BookingTicket_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'book_BookingTicket';
	var $object_name = 'book_BookingTicket';
	var $table_name = 'book_bookingticket';
	var $importable = true;
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $team_id;
		var $team_set_id;
		var $team_count;
		var $team_name;
		var $team_link;
		var $team_count_link;
		var $teams;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $status;
		var $booking_code;
		var $booking_date;
		var $serial_no;
		var $invoice_no;
		var $invoice_date;
		var $address_street;
		var $address_city;
		var $address_state;
		var $address_postalcode;
		var $address_country;
		var $taxcode;
		var $booking_type;
		var $payment_date_1;
		var $payment_amount_1;
		var $currency_id;
		var $payment_date_2;
		var $payment_amount_2;
		var $full_payment_date;
		var $total_amount;
		var $payment_plan;
		var $total_purchase;
		var $payment_balance;
		var $accountant_balance;
		
	/**
	 * This is a depreciated method, please start using __construct() as this method will be removed in a future version
     *
     * @see __construct
     * @depreciated
	 */
	function book_BookingTicket_sugar(){
		self::__construct();
	}

	public function __construct(){
		parent::__construct();
	}
	
	public function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>