<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_ticket_modified_user' => 
  array (
    'id' => '14f4782b-b92d-1e7a-0606-55b83ec989ba',
    'relationship_name' => 'c_ticket_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_ticket_created_by' => 
  array (
    'id' => '1ed67826-efb0-3e53-35fc-55b83ef67bed',
    'relationship_name' => 'c_ticket_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_ticket_assigned_user' => 
  array (
    'id' => '4dda6287-d04d-a20f-5579-55b83e317931',
    'relationship_name' => 'c_ticket_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_c_ticket_1' => 
  array (
    'id' => '50f88a07-848f-34e8-1009-55b83efe3787',
    'relationship_name' => 'accounts_c_ticket_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'id',
    'join_table' => 'accounts_c_ticket_1_c',
    'join_key_lhs' => 'accounts_c_ticket_1accounts_ida',
    'join_key_rhs' => 'accounts_c_ticket_1c_ticket_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_c_ticket_1' => 
  array (
    'id' => '7cc8d216-f465-610f-8396-55b83ed83ed0',
    'relationship_name' => 'contacts_c_ticket_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'id',
    'join_table' => 'contacts_c_ticket_1_c',
    'join_key_lhs' => 'contacts_c_ticket_1contacts_ida',
    'join_key_rhs' => 'contacts_c_ticket_1c_ticket_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_c_ticket_2' => 
  array (
    'id' => '87812235-7798-2669-a55f-55b83e2cad05',
    'relationship_name' => 'contacts_c_ticket_2',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'id',
    'join_table' => 'contacts_c_ticket_2_c',
    'join_key_lhs' => 'contacts_c_ticket_2contacts_ida',
    'join_key_rhs' => 'contacts_c_ticket_2c_ticket_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_bookingticket_c_ticket_1' => 
  array (
    'id' => 'b2666417-e69b-2af1-7ed1-55b83e42293d',
    'relationship_name' => 'c_bookingticket_c_ticket_1',
    'lhs_module' => 'C_BookingTicket',
    'lhs_table' => 'c_bookingticket',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Ticket',
    'rhs_table' => 'c_ticket',
    'rhs_key' => 'id',
    'join_table' => 'c_bookingticket_c_ticket_1_c',
    'join_key_lhs' => 'c_bookingticket_c_ticket_1c_bookingticket_ida',
    'join_key_rhs' => 'c_bookingticket_c_ticket_1c_ticket_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_ticket_c_ticket_1' => 
  array (
    'rhs_label' => 'Ticket',
    'lhs_label' => 'Ticket',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'C_Ticket',
    'rhs_module' => 'C_Ticket',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_ticket_c_ticket_1',
  ),
);