<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_BookingTicket'] = array(
        'table'=>'C_bookingticket',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'status' => 
            array (
                'required' => true,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'comments' => '',
                'help' => 'Status',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_booking_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
                'default' => 'WaitingList',
                'massupdate' => 0,
            ),
            'payment_status' => 
            array (
                'name' => 'payment_status',
                'vname' => 'LBL_PAYMENT_STATUS',
                'type' => 'enum',
                'comments' => '',
                'help' => 'Payment Status',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'payment_status_booking_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
                'default' => 'Paid',
                'massupdate' => 0,
            ),

            'booking_date' => 
            array (
                'required' => false,
                'name' => 'booking_date',
                'vname' => 'LBL_BOOKING_DATE',
                'type' => 'date',
                'no_default' => false,
                'comments' => '',
                'help' => 'Booking Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
                'massupdate' => 0,
            ),
            'inspected_payment_date' => 
            array (
                'required' => false,
                'name' => 'inspected_payment_date',
                'vname' => 'LBL_EXPECTED_DATE',
                'type' => 'date',
                'no_default' => false,
                'comments' => '',
                'help' => 'Inspected Payment Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
                'massupdate' => 0,
            ),

            'serial_no' => 
            array (
                'required' => false,
                'name' => 'serial_no',
                'vname' => 'LBL_SERIAL_NO',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Serial No',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'invoice_no' => 
            array (
                'required' => false,
                'name' => 'invoice_no',
                'vname' => 'LBL_INVOICE_NO',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice No',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'invoice_date' => 
            array (
                'required' => false,
                'name' => 'invoice_date',
                'vname' => 'LBL_INVOICE_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Invoice Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
            ),
            'internal_doc_id' => 
            array (
                'required' => false,
                'name' => 'internal_doc_id',
                'vname' => 'LBL_INTERNAL_DOC_ID',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Internal Document ID',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => true,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'customer_code' => 
            array (
                'required' => false,
                'name' => 'customer_code',
                'vname' => 'LBL_CUSTOMER_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Customer Code',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'address' => 
            array (
                'name' => 'address',
                'vname' => 'LBL_ADDRESS',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Address',
                'importable' => 'true',
                'len' => 100,
                'size' => '20',
                'rows' => '3',
                'cols' => '60',
            ),
            'taxcode' => 
            array (
                'required' => false,
                'name' => 'taxcode',
                'vname' => 'LBL_TAXCODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Taxcode',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'booking_type' => 
            array (
                'required' => true,
                'name' => 'booking_type',
                'vname' => 'LBL_BOOKING_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' =>'Normal',
                'comments' => '',
                'help' => 'Booking Type',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'booking_type_booking_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'description' => 
            array (
                'name' => 'description',
                'vname' => 'LBL_DESCRIPTION',
                'type' => 'text',
                'comment' => 'Full text of the note',
                'rows' => '3',
                'cols' => '60',
                'required' => false,
                'massupdate' => 0,
                'no_default' => false,
                'comments' => 'Full text of the note',
                'help' => 'Description',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
            ),
            'payment_date_1' => 
            array (
                'required' => false,
                'name' => 'payment_date_1',
                'vname' => 'LBL_PAYMENT_DATE_1',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Date 1',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'payment_amount_1' => 
            array (
                'required' => false,
                'name' => 'payment_amount_1',
                'vname' => 'LBL_PAYMENT_AMOUNT_1',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount 1',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY_UNIT',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'payment_date_2' => 
            array (
                'required' => false,
                'name' => 'payment_date_2',
                'vname' => 'LBL_PAYMENT_DATE_2',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Date 2',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'payment_amount_2' => 
            array (
                'required' => false,
                'name' => 'payment_amount_2',
                'vname' => 'LBL_PAYMENT_AMOUNT_2',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount 2',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'full_payment_date' => 
            array (
                'required' => false,
                'name' => 'full_payment_date',
                'vname' => 'LBL_FULL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Full-payment Date',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'total_amount' => 
            array (
                'required' => false,
                'name' => 'total_amount',
                'vname' => 'LBL_TOTAL_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Total Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'total_profit' => 
            array (
                'required' => false,
                'name' => 'total_profit',
                'vname' => 'LBL_TOTAL_PROFIT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Total Profit',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payment_plan' => 
            array (
                'required' => false,
                'name' => 'payment_plan',
                'vname' => 'LBL_PAYMENT_PLAN',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Plan',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'total_purchase' => 
            array (
                'required' => false,
                'name' => 'total_purchase',
                'vname' => 'LBL_TOTAL_PURCHASE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Total Purchase',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payment_balance' => 
            array (
                'required' => false,
                'name' => 'payment_balance',
                'vname' => 'LBL_PAYMENT_BALANCE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Balance',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'accountant_balance' => 
            array (
                'required' => false,
                'name' => 'accountant_balance',
                'vname' => 'LBL_ACCOUNTANT_BALANCE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Accountant Balance',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payment_method_1' => array(
                'name' => 'payment_method_1',
                'vname' => 'LBL_PAYMENT_METHOD_1',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'payment_method_2' => array(
                'name' => 'payment_method_2',
                'vname' => 'LBL_PAYMENT_METHOD_2',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'full_payment_method' => array(
                'name' => 'full_payment_method',
                'vname' => 'LBL_FULL_PAYMENT_METHOD',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_options',
                'studio' => 'visible',
                'dependency' => false,
            ),
            //Related Field  - Fisrt Aproach
            'user_sale' =>  array (
                'required' => true,
                'name' => 'user_sale',
                'vname' => 'LBL_USER_SALE',
                'type' => 'relate',
                'reportable'=>false,
                'link' => 'users_sale',
                'rname' => 'name',
                'table' => 'users',
                'id_name' => 'user_sale_id',
                'module'=>'Users',
                'duplicate_merge'=>'disabled',
                'importable' => 'false',
                'massupdate' => false,
                'massupdate' => 0,
            ),
            'user_sale_id' =>  array (
                'required' => true,
                'name' => 'user_sale_id',
                'rname' => 'user_sale',
                'id_name' => 'user_sale_id',
                'vname' => 'LBL_USER_SALE_ID',
                'type' => 'assigned_user_name',
                'table' => 'users',
                'isnull' => 'false',
                'dbType' => 'id',
                'group'=>'user_sale',
                'comment' => 'User who sale ticket',
                'massupdate' => false,
                'massupdate' => 0,
            ),
            'users_sale' =>  array (
                'name' => 'users_sale',
                'type' => 'link',
                'relationship' => 'users_sale',
                'vname' => 'LBL_USER_SALE',
                'link_type' => 'one',
                'module'=>'Users',
                'bean_name'=>'User',
                'source'=>'non-db',
                'massupdate' => 0,
            ),
            //End Field User Sale
            'sale_email' => 
            array (
                'required' => false,
                'name' => 'sale_email',
                'vname' => 'LBL_SALE_EMAIL',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Sale Email',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'parent_name' => array(
                'name' => 'parent_name',
                'vname' => 'LBL_PARENT_NAME',
                'type' => 'parent',
                'massupdate' => 0,
                'dbtype' => 'varchar',
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'len' => 100,
                'size' => '20',
                'options' => 'flexparent_booking_hotel_list',
                'studio' => 'visible',
                'type_name' => 'parent_type',
                'id_name' => 'parent_id',
                'parent_type' => 'flexparent_booking_hotel_list',
            ),
            'parent_type' => array(
                'required' => false,
                'name' => 'parent_type',
                'vname' => 'LBL_PARENT_TYPE',
                'type' => 'parent_type',
                'massupdate' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => true,
                'reportable' => true,
                'len' => 255,
                'size' => '20',
                'default' => 'Contacts',
                'dbType' => 'varchar',
                'studio' => 'hidden',
            ),
            'parent_id' => array(
                'required' => false,
                'name' => 'parent_id',
                'vname' => 'LBL_PARENT_ID',
                'type' => 'id',
                'massupdate' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'len' => 36,
                'size' => '20',
            ),
            'phone' => 
            array (
                'name' => 'phone',
                'vname' => 'LBL_PHONE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Phone',
                'importable' => 'true',
                'len' => 100,
                'size' => '20',
            ),
            'ticket_info'  => array (
                'name' => 'ticket_info',
                'vname' => 'LBL_TICKET_INFO',
                'type' => 'varchar',
                'source'=>'non-db',
                'audited'=>true,
            ),
            'currency' => 
            array (
                'required' => true,
                'name' => 'currency',
                'vname' => 'LBL_CURRENCY',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'VND',
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 30,
                'size' => '20',
                'options' => 'currency_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'ex_rate' => 
            array (
                'required' => false,
                'name' => 'ex_rate',
                'vname' => 'LBL_EX_RATE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Ex rate',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '13',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            'invoice_content' => array(
                'name' => 'invoice_content',
                'type' => 'varchar',
                'help' => 'Invoice Content',
                'len' => 225,
                'size' => 20,
                'vname' => 'LBL_INVOICE_CONTENT',
                'massupdate' => 0,
            ),
            'total_amount_invoice' => array(
                'required' => false,
                'name' => 'total_amount_invoice',
                'vname' => 'LBL_TOTAL_AMOUNT_INVOICE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Total Amount Invoice',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'company' => array(
                'name' =>'company',
                'type' => 'varchar',
                'len' => '100',
                'size' => 20,
                'vname' =>'LBL_COMPANY',
                'massupdate' => 0,
            ),
            'category' => 
            array (
                'required' => false,
                'name' => 'category',
                'vname' => 'LBL_CATEGORY',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Category',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'category_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'sub_category' => 
            array (
                'required' => false,
                'name' => 'sub_category',
                'vname' => 'LBL_SUB_CATEGORY',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Sub Category',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'sub_category_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ), 
            'supplier' => 
            array (
                'required' => false,
                'name' => 'supplier',
                'vname' => 'LBL_SUPPLIER',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Supplier',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'supplier_ticket_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'airline' => 
            array (
                'required' => false,
                'name' => 'airline',
                'vname' => 'LBL_ASSET',
                'type' => 'enum',
                'massupdate' => 0,
                'comments' => '',
                'help' => 'Airline',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'options' => 'asset_ticket_list',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'tour' => 
            array (
                'required' => false,
                'name' => 'tour',
                'vname' => 'LBL_TOUR',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Tour',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => true,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'io_code' => 
            array (
                'name' => 'io_code',
                'vname' => 'LBL_IO_CODE',
                'type' => 'enum',
                'comments' => '',
                'help' => 'Mã nhập xuất',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'full_IO_code_list',
                'studio' => 'visible',
                'dependency' => false,
                'massupdate' => 0,
            ),
            'unit_code' => 
            array (
                'required' => false,
                'name' => 'unit_code',
                'vname' => 'LBL_UNIT_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '10',
                'size' => '20',
            ),
            'gs_code' =>
            array (
                'name' => 'gs_code',
                'vname' => 'LBL_GS_CODE',
                'type' => 'enum',
                'options' => 'gs_code_vardef_options',
            ),
            'refund_date' => 
            array (
                'name' => 'refund_date',
                'vname' => 'LBL_REFUND_DATE',
                'type' => 'date',
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
                'massupdate' => 0,
            ),
            'tcc_code' => 
            array (
                'required' => false,
                'name' => 'tcc_code',
                'vname' => 'LBL_TCC_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => true,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
        ),
        'relationships'=>array (
            //Relationship User Sale
            'users_sale' => array(
                'lhs_module'=> 'Users', 
                'lhs_table'=> 'users', 
                'lhs_key' => 'id',
                'rhs_module'=> 
                'C_BookingTicket', 
                'rhs_table'=> 'c_bookingticket', 
                'rhs_key' => 'user_sale_id',
                'relationship_type'=>'one-to-many')

        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_BookingTicket','C_BookingTicket', array('basic','team_security','assignable'));